### ISSUE TITLE
Map Randomizer

### ISSUE THREAD

**Issue by erik-lance** [erik-lance/Cataclysm-Digital-Companion#3]
Create a file under `/src/utils/` called `randomizer.ts`.

This will be the helper file for randomizing the map obstacles (walls and destructibles). We generate an int[][] array similar to the format in #5 . This file simply provides a map data randomizer function.

- [x] #9
- [x] Sets up destructibles
- [ ] Sets up player positions (Note: awaiting instruction if we'll keep this)

**Comment by johnwhoyou** [comment]
Implemented in 48f7c5f27ad39a1b77744c3d4aaa2319a4e1f21f
